################################################ Server 설정 ################################################
server:
  port: 8080

################################################ SPRING BOOT ################################################
spring:
  profiles:
    active: local

  application:
    name: boot-generator

  # ============================ DB 자동 설정 제거 =======================================
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration # jpa
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration # jpa

# ==================================== Swagger 설정 ====================================
springdoc:
  auto-response-codes: false
  swagger-ui:
    path: /swagger
  api-docs:
    path: /swagger/docs
    groups:
      enabled: true
  cache:
    disabled: true
  api-info:
    title: Boot Generator
    description: API in/out for AMIS 3.0
    version: 1.0.0
    terms-of-service: http://bootgen.com/termsofservice
    contact:
      name: Administrator
      url: https://bootgen.com
      email: admin@bootgen.com
    license:
      name: MIT License
      url: https://bootgen.com/license

generator:
  base-path: '..'
  project:
    - name: test-backend
      group: bootgen-com
      architecture: mvc #mvc/crs/qrs
      orm: jpa #jpa/mybatis or blank if no datasource applicable
      hikari-config:
        driver-class-name: 'org.postgresql.Driver' # designed to use PostgreSQL
        jdbc-url: 'jdbc:postgresql://192.168.50.210:5432/home'
        username: 'admin'
        password: 'admin'
      schema-filter: 'public' # must set full name
      table-filter: '%' # set '%' for all
      column-filter: '%' # rather not change
      destination-path: "file:${generator.base-path}/test-backend-service"
      local-port: 7070
    - name: notification-stream
      group: bootgen-com
      architecture: mvc #mvc/crs/qrs
      orm:
      table-filter: '%' # set '%' for all
      column-filter: '%' # rather not change
      destination-path: "file:${generator.base-path}/notification-stream-service"
      local-port: 7071